"""empty message

Revision ID: 858a52e645da
Revises: 3ba8bd58c11b
Create Date: 2025-05-01 19:34:28.359565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858a52e645da'
down_revision = '3ba8bd58c11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_oriented', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('family_oriented')

    # ### end Alembic commands ###
